version: "3.9"

services:
  web:
    build: .
    container_name: reporting_app
    command: python manage.py runserver 0.0.0.0:8900
    ports:
      - "8900:8900"
    volumes:
      - .:/app
    environment:
      - DEBUG=0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/reporting_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: reporting_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reporting_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: reporting_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # login email
      PGADMIN_DEFAULT_PASSWORD: admin          # login password
    ports:
      - "5050:80"   # youâ€™ll access pgAdmin at http://localhost:5050
    depends_on:
      - db

volumes:
  postgres_data:
